name:                parsiuk
version:             0.0.2.0
github:              "drula/parsiuk"
license:             LGPL-3
author:              "Andrey Dudinov"
maintainer:          "adudinov@yandex.by"
copyright:           "2018 Andrey Dudinov"

extra-source-files:
- README.md
- ChangeLog.md
- src/Lex.x

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/drula/parsiuk#readme>

dependencies:
- base >= 4.7 && < 5
- array
- filepath

library:
  source-dirs: src

executables:
  parsiuk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parsiuk

tests:
  parsiuk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parsiuk
    - tasty
    - tasty-hunit
